name: deploy
permissions:
    contents: read
    packages: write
on:
    push:
        branches:
          - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
            with:
                submodules: recursive
                ssh-key: ${{ secrets.SSH_KEY }}
          - uses: docker/setup-buildx-action@v2
          - uses: docker/login-action@v2
            with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
          - name: get image name
            shell: bash
            run: echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
          - name: add ssh key
            shell: bash
            run: |
                eval $(ssh-agent)
                echo "${{ secrets.SSH_KEY }}" > ./id_ed25519
                ssh-add ./id_ed25519
          - name: build & push
            uses: docker/build-push-action@v4
            with:
                push: true
                tags: ghcr.io/${{ env.REPO }}:${{ github.sha }},ghcr.io/${{ env.REPO }}:latest
                file: ./Dockerfile
                ssh: ${{ env.SSH_AUTH_SOCK }}